stages:
- build
- test
- deploy

# Build Docker image
build_image:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - echo "Building Docker Image..."
    - docker build --provenance=false --platform linux/amd64 -t $ECR_REPOSITORY:$CI_COMMIT_SHORT_SHA ./math-engine
    - echo "Build completed."

# Test build
test_build:
  stage: test
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    - echo "Testing Docker build..."
    - docker build --provenance=false --platform linux/amd64 -t verify-build ./math-engine
    - echo "Test successful."
  needs: ["build_image"]

# Push image to AWS ECR
deploy_ecr:
  stage: deploy
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - apk add --no-cache python3 py3-pip
    - pip install awscli
  script:
    - echo "Starting Deployment to ECR..."

    # Needs to build again for the image to also exist in this job
    - docker build --provenance=false --platform linux/amd64 -t $ECR_REPOSITORY:$CI_COMMIT_SHORT_SHA ./math-engine

    - echo "Authenticating with AWS..."
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

    # Rename local Docker image to match AWS ECR repository path 
    # (Docker pushes require images to be named according to the remote registry)
    - echo "Tagging image for ECR..."
    - docker tag $ECR_REPOSITORY:$CI_COMMIT_SHORT_SHA $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY:$CI_COMMIT_SHORT_SHA

    - echo "Pushing image to ECR..."
    - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY:$CI_COMMIT_SHORT_SHA

    - echo "Deployment (ECR) Successfully Completed."
  needs: ["test_build"]

# Deploy to Kubernetes
# TODO: Consider CronJobs
deploy_k8s:
  stage: deploy
  image: google/cloud-sdk:latest
  before_script:
      # Create k8 config directory, reconstruct kubeconfig file inside CI container. kubectl then knows
      #  which EKS cluster to talk to, cluster endpoint, certificate authority, & authentication method.
      - mkdir -p ~/.kube
      - echo "$KUBECONFIG_CONTENT" | base64 -d > ~/.kube/config

      # Install AWS CLI v2
      - apt-get update && apt-get install -y curl unzip
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ./aws/install
      - aws --version

      # Export AWS credentials for kubectl exec auth
      - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION

      # Force AWS IAM plugin to run once before kubectl tries to use it
      - aws eks get-token --region $AWS_DEFAULT_REGION --cluster-name schrodinger-cluster > /dev/null

  script:
    - echo "(k8 Job) Testing AWS CLI..."
    - aws sts get-caller-identity

    # Jobs are immutable in Kubernetes, so delete old one first. Still safe if job DNE
    - kubectl delete job schrodinger-job -n schrodinger || true  

    # Re/create job
    - kubectl apply -f schrodinger-job.yaml

    - echo "Setting Redis env vars..."
    - kubectl set env job/schrodinger-job REDIS_HOST=$REDIS_HOST REDIS_PORT=6379 -n schrodinger

    - echo "Updating image..."
    - kubectl set image job/schrodinger-job worker=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY:$CI_COMMIT_SHORT_SHA -n schrodinger

    - echo "Deployment (Kubernetes) Successfully Completed."

  needs: ["deploy_ecr"]
