apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: schrodinger-cluster
  region: us-west-2

managedNodeGroups:
  - name: worker-nodes
    instanceType: t3.medium
    desiredCapacity: 3
    minSize: 3
    maxSize: 5
    availabilityZones:
      - us-west-2a

# Run:    eksctl create cluster -f cluster.yaml
# Verify: kubectl get nodes
