apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-0a9fa6ef651226cca # EFS ID
  directoryPerms: "700"